/**
 * G&G Cleaning Services — Operational ZIP Code Registry
 * Deterministic service area allowlist for Nassau and Suffolk Counties, Long Island, NY.
 */

export const LONG_ISLAND_ZIP_REGISTRY = {
  // --- NASSAU COUNTY ---
  // Floral Park, New Hyde Park, Elmont
  "11001": { county: "Nassau", marketArea: "Floral Park" },
  "11002": { county: "Nassau", marketArea: "Floral Park" },
  "11003": { county: "Nassau", marketArea: "Elmont" },
  "11004": { county: "Nassau", marketArea: "Glen Oaks / Floral Park" },
  "11005": { county: "Nassau", marketArea: "Floral Park" },
  // Great Neck & Peninsula
  "11020": { county: "Nassau", marketArea: "Great Neck" },
  "11021": { county: "Nassau", marketArea: "Great Neck" },
  "11022": { county: "Nassau", marketArea: "Great Neck" },
  "11023": { county: "Nassau", marketArea: "Great Neck" },
  "11024": { county: "Nassau", marketArea: "Great Neck / Kings Point" },
  "11026": { county: "Nassau", marketArea: "Great Neck" },
  "11027": { county: "Nassau", marketArea: "Great Neck" },
  // Manhasset, Port Washington, Roslyn
  "11030": { county: "Nassau", marketArea: "Manhasset" },
  "11040": { county: "Nassau", marketArea: "New Hyde Park" },
  "11042": { county: "Nassau", marketArea: "New Hyde Park" },
  "11050": { county: "Nassau", marketArea: "Port Washington" },
  "11096": { county: "Nassau", marketArea: "Inwood" },
  // Garden City, Mineola, Westbury, Hempstead
  "11501": { county: "Nassau", marketArea: "Mineola" },
  "11507": { county: "Nassau", marketArea: "Albertson" },
  "11509": { county: "Nassau", marketArea: "Atlantic Beach" },
  "11510": { county: "Nassau", marketArea: "Baldwin" },
  "11514": { county: "Nassau", marketArea: "Carle Place" },
  "11516": { county: "Nassau", marketArea: "Cedarhurst" },
  "11518": { county: "Nassau", marketArea: "East Rockaway" },
  "11520": { county: "Nassau", marketArea: "Freeport" },
  "11530": { county: "Nassau", marketArea: "Garden City" },
  "11531": { county: "Nassau", marketArea: "Garden City" },
  "11542": { county: "Nassau", marketArea: "Glen Cove" },
  "11545": { county: "Nassau", marketArea: "Glen Head" },
  "11547": { county: "Nassau", marketArea: "Glenwood Landing" },
  "11548": { county: "Nassau", marketArea: "Greenvale" },
  "11549": { county: "Nassau", marketArea: "Hempstead" },
  "11550": { county: "Nassau", marketArea: "Hempstead" },
  "11551": { county: "Nassau", marketArea: "Hempstead" },
  "11552": { county: "Nassau", marketArea: "West Hempstead" },
  "11553": { county: "Nassau", marketArea: "Uniondale" },
  "11554": { county: "Nassau", marketArea: "East Meadow" },
  "11555": { county: "Nassau", marketArea: "East Meadow" },
  "11556": { county: "Nassau", marketArea: "East Meadow" },
  "11557": { county: "Nassau", marketArea: "Hewlett" },
  "11558": { county: "Nassau", marketArea: "Island Park" },
  "11559": { county: "Nassau", marketArea: "Lawrence" },
  "11560": { county: "Nassau", marketArea: "Locust Valley" },
  "11561": { county: "Nassau", marketArea: "Long Beach" },
  "11563": { county: "Nassau", marketArea: "Lynbrook" },
  "11565": { county: "Nassau", marketArea: "Malverne" },
  "11566": { county: "Nassau", marketArea: "Merrick" },
  "11568": { county: "Nassau", marketArea: "Old Westbury" },
  "11569": { county: "Nassau", marketArea: "Point Lookout" },
  "11570": { county: "Nassau", marketArea: "Rockville Centre" },
  "11571": { county: "Nassau", marketArea: "Rockville Centre" },
  "11572": { county: "Nassau", marketArea: "Oceanside" },
  "11575": { county: "Nassau", marketArea: "Roosevelt" },
  "11576": { county: "Nassau", marketArea: "Roslyn" },
  "11577": { county: "Nassau", marketArea: "Roslyn Heights" },
  "11579": { county: "Nassau", marketArea: "Sea Cliff" },
  "11580": { county: "Nassau", marketArea: "Valley Stream" },
  "11581": { county: "Nassau", marketArea: "Valley Stream" },
  "11582": { county: "Nassau", marketArea: "Valley Stream" },
  "11590": { county: "Nassau", marketArea: "Westbury" },
  "11596": { county: "Nassau", marketArea: "Williston Park" },
  "11598": { county: "Nassau", marketArea: "Woodmere" },
  "11709": { county: "Nassau", marketArea: "Bayville" },
  "11714": { county: "Nassau", marketArea: "Bethpage" },
  "11732": { county: "Nassau", marketArea: "East Norwich" },
  "11753": { county: "Nassau", marketArea: "Jericho" },
  "11756": { county: "Nassau", marketArea: "Levittown" },
  "11758": { county: "Nassau", marketArea: "Massapequa" },
  "11762": { county: "Nassau", marketArea: "Massapequa Park" },
  "11765": { county: "Nassau", marketArea: "Locust Valley" },
  "11771": { county: "Nassau", marketArea: "Oyster Bay" },
  "11783": { county: "Nassau", marketArea: "Seaford" },
  "11791": { county: "Nassau", marketArea: "Syosset" },
  "11793": { county: "Nassau", marketArea: "Wantagh" },
  "11797": { county: "Nassau", marketArea: "Woodbury" },
  "11801": { county: "Nassau", marketArea: "Hicksville" },
  "11802": { county: "Nassau", marketArea: "Hicksville" },
  "11803": { county: "Nassau", marketArea: "Plainview" },
  "11804": { county: "Nassau", marketArea: "Old Bethpage" },

  // --- SUFFOLK COUNTY ---
  "11701": { county: "Suffolk", marketArea: "Amityville" },
  "11702": { county: "Suffolk", marketArea: "Babylon" },
  "11703": { county: "Suffolk", marketArea: "North Babylon" },
  "11704": { county: "Suffolk", marketArea: "West Babylon" },
  "11705": { county: "Suffolk", marketArea: "Bayshore" },
  "11706": { county: "Suffolk", marketArea: "Bay Shore" },
  "11713": { county: "Suffolk", marketArea: "Bellport" },
  "11715": { county: "Suffolk", marketArea: "Blue Point" },
  "11716": { county: "Suffolk", marketArea: "Bohemia" },
  "11717": { county: "Suffolk", marketArea: "Brentwood" },
  "11718": { county: "Suffolk", marketArea: "Brightwaters" },
  "11719": { county: "Suffolk", marketArea: "Brookhaven" },
  "11720": { county: "Suffolk", marketArea: "Centereach" },
  "11721": { county: "Suffolk", marketArea: "Centerport" },
  "11722": { county: "Suffolk", marketArea: "Central Islip" },
  "11724": { county: "Suffolk", marketArea: "Cold Spring Harbor" },
  "11725": { county: "Suffolk", marketArea: "Commack" },
  "11726": { county: "Suffolk", marketArea: "Copiague" },
  "11727": { county: "Suffolk", marketArea: "Coram" },
  "11729": { county: "Suffolk", marketArea: "Deer Park" },
  "11730": { county: "Suffolk", marketArea: "East Islip" },
  "11731": { county: "Suffolk", marketArea: "East Northport" },
  "11733": { county: "Suffolk", marketArea: "Setauket" },
  "11735": { county: "Suffolk", marketArea: "Farmingdale" },
  "11738": { county: "Suffolk", marketArea: "Farmingville" },
  "11739": { county: "Suffolk", marketArea: "Great River" },
  "11740": { county: "Suffolk", marketArea: "Greenlawn" },
  "11741": { county: "Suffolk", marketArea: "Holbrook" },
  "11742": { county: "Suffolk", marketArea: "Holtsville" },
  "11743": { county: "Suffolk", marketArea: "Huntington" },
  "11746": { county: "Suffolk", marketArea: "Dix Hills / Huntington Station" },
  "11747": { county: "Suffolk", marketArea: "Melville" },
  "11749": { county: "Suffolk", marketArea: "Islandia" },
  "11751": { county: "Suffolk", marketArea: "Islip" },
  "11752": { county: "Suffolk", marketArea: "Islip Terrace" },
  "11754": { county: "Suffolk", marketArea: "Kings Park" },
  "11755": { county: "Suffolk", marketArea: "Lake Grove" },
  "11757": { county: "Suffolk", marketArea: "Lindenhurst" },
  "11763": { county: "Suffolk", marketArea: "Medford" },
  "11764": { county: "Suffolk", marketArea: "Miller Place" },
  "11766": { county: "Suffolk", marketArea: "Mount Sinai" },
  "11767": { county: "Suffolk", marketArea: "Nesconset" },
  "11768": { county: "Suffolk", marketArea: "Northport" },
  "11769": { county: "Suffolk", marketArea: "Oakdale" },
  "11770": { county: "Suffolk", marketArea: "Ocean Beach" },
  "11772": { county: "Suffolk", marketArea: "Patchogue" },
  "11776": { county: "Suffolk", marketArea: "Port Jefferson" },
  "11777": { county: "Suffolk", marketArea: "Port Jefferson Station" },
  "11778": { county: "Suffolk", marketArea: "Rocky Point" },
  "11779": { county: "Suffolk", marketArea: "Ronkonkoma" },
  "11780": { county: "Suffolk", marketArea: "Saint James" },
  "11782": { county: "Suffolk", marketArea: "Sayville" },
  "11784": { county: "Suffolk", marketArea: "Selden" },
  "11786": { county: "Suffolk", marketArea: "Shoreham" },
  "11787": { county: "Suffolk", marketArea: "Smithtown" },
  "11788": { county: "Suffolk", marketArea: "Hauppauge" },
  "11789": { county: "Suffolk", marketArea: "Sound Beach" },
  "11790": { county: "Suffolk", marketArea: "Stony Brook" },
  "11792": { county: "Suffolk", marketArea: "Wading River" },
  "11794": { county: "Suffolk", marketArea: "Stony Brook University" },
  "11795": { county: "Suffolk", marketArea: "West Islip" },
  "11796": { county: "Suffolk", marketArea: "West Sayville" },
  "11798": { county: "Suffolk", marketArea: "Wyandanch" },
  // East End & North Fork
  "11901": { county: "Suffolk", marketArea: "Riverhead" },
  "11933": { county: "Suffolk", marketArea: "Calverton" },
  "11934": { county: "Suffolk", marketArea: "Center Moriches" },
  "11935": { county: "Suffolk", marketArea: "Cutchogue" },
  "11937": { county: "Suffolk", marketArea: "East Hampton" },
  "11940": { county: "Suffolk", marketArea: "East Moriches" },
  "11941": { county: "Suffolk", marketArea: "East Quogue" },
  "11942": { county: "Suffolk", marketArea: "Eastport" },
  "11944": { county: "Suffolk", marketArea: "Greenport" },
  "11946": { county: "Suffolk", marketArea: "Hampton Bays" },
  "11949": { county: "Suffolk", marketArea: "Manorville" },
  "11950": { county: "Suffolk", marketArea: "Mastic" },
  "11951": { county: "Suffolk", marketArea: "Mastic Beach" },
  "11952": { county: "Suffolk", marketArea: "Mattituck" },
  "11953": { county: "Suffolk", marketArea: "Middle Island" },
  "11954": { county: "Suffolk", marketArea: "Montauk" },
  "11955": { county: "Suffolk", marketArea: "New Suffolk" },
  "11957": { county: "Suffolk", marketArea: "Orient" },
  "11959": { county: "Suffolk", marketArea: "Peconic" },
  "11961": { county: "Suffolk", marketArea: "Ridge" },
  "11963": { county: "Suffolk", marketArea: "Sag Harbor" },
  "11964": { county: "Suffolk", marketArea: "Shelter Island" },
  "11965": { county: "Suffolk", marketArea: "Shelter Island Heights" },
  "11967": { county: "Suffolk", marketArea: "Shirley" },
  "11968": { county: "Suffolk", marketArea: "Southampton" },
  "11970": { county: "Suffolk", marketArea: "South Jamesport" },
  "11971": { county: "Suffolk", marketArea: "Southold" },
  "11973": { county: "Suffolk", marketArea: "Speonk" },
  "11976": { county: "Suffolk", marketArea: "Water Mill" },
  "11977": { county: "Suffolk", marketArea: "Westhampton" },
  "11978": { county: "Suffolk", marketArea: "Westhampton Beach" },
  "11980": { county: "Suffolk", marketArea: "Yaphank" }
};
